package com.strux.auth_service.dto;

public enum AuditEvent {
    // Registration
    USER_REGISTERED,
    REGISTRATION_BLOCKED_GEO,
    REGISTRATION_FAILED,

    // Login
    LOGIN_SUCCESS,
    LOGIN_FAILED,
    LOGIN_ACCOUNT_LOCKED,
    LOGIN_BLOCKED_GEO,
    LOGIN_CAPTCHA_FAILED,
    LOGIN_ERROR,

    // 2FA
    LOGIN_2FA_REQUIRED,
    LOGIN_2FA_SUCCESS,
    LOGIN_2FA_FAILED,

    // Token
    TOKEN_REFRESHED,
    TOKEN_REFRESH_FAILED,

    // Logout
    LOGOUT_SUCCESS,
    LOGOUT_ERROR,

    // Security
    RATE_LIMIT_EXCEEDED,
    SUSPICIOUS_ACTIVITY,
    SESSION_REMOVED,

    // Account Management
    ACCOUNT_DELETED,
    PASSWORD_CHANGED,

    // ✅ Email Verification (YENİ)
    EMAIL_VERIFIED,
    EMAIL_VERIFICATION_FAILED,

    // ✅ Password Reset (YENİ)
    PASSWORD_RESET_REQUESTED,
    PASSWORD_RESET_SUCCESS,
    PASSWORD_RESET_FAILED
}