package com.strux.auth_service.dto;

public enum AuditEvent {
    USER_REGISTERED,
    REGISTRATION_BLOCKED_GEO,
    LOGIN_SUCCESS,
    LOGIN_FAILED,
    LOGIN_ACCOUNT_LOCKED,
    LOGIN_BLOCKED_GEO,
    LOGIN_CAPTCHA_FAILED,
    LOGIN_2FA_REQUIRED,
    LOGIN_2FA_SUCCESS,
    LOGIN_2FA_FAILED,
    LOGIN_ERROR,
    RATE_LIMIT_EXCEEDED,
    SESSION_REMOVED,
    SUSPICIOUS_ACTIVITY,
    PASSWORD_CHANGED,
    TOKEN_REFRESH_FAILED, TOKEN_REFRESHED, LOGOUT_SUCCESS, LOGOUT_ERROR, ACCOUNT_DELETED
}